export const config = {
    "default_guide_star_table_columns": [
        "actions",
        "target_name",
        "ra",
        "dec",
        "equinox",
        "h_mag",
        "v_mag",
        "r_mag",
        "j_mag",
        "k_mag",
        "separation",
    ],
    "default_table_columns": {
        "non_ao": [
            "actions",
            "priority",
            "target_name",
            "ra",
            "dec",
            "equinox",
            "r_mag",
            "h_mag",
            "pm_ra",
            "pm_dec",
            "semids",
            "rotator_pa",
            "comment",
            "tags"
        ],
        "ao": [
            "actions",
            "priority",
            "target_name",
            "ra",
            "dec",
            "equinox",
            "lgs",
            "r_mag",
            "h_mag",
            "science_target",
            "separation",
            "semids",
            "rotator_pa",
            "comment",
            "tags"
        ],
    },
    "csv_order": [
        "target_name",
        "ra",
        "dec",
        "equinox",
        "j_mag",
        "g_mag",
        "pm_ra",
        "pm_dec",
        "comment",
        "tic_id",
        "gaia_id",
        "ra_deg",
        "dec_deg",
        "observer_id",
        "semids",
        "tags"
    ],
    "pinned_table_columns": {
        "left": [
            "selected",
            "actions",
            "priority",
            "target_name",
            "ra",
            "dec",
            "equinox",
        ],
        "right": ["tags"]
    },
    "gsc240_catalog_to_target_map": {
    "HSTID": "target_name" ,
    "RA": "ra",
    "Decl": "dec",
    "PmRA": "pm_ra",
    "PmDec": "pm_dec",
    "Vmag": "v_mag",
    "Bmag": "b_mag",
    "Rmag": "r_mag",
    "Imag": "i_mag",
    "Jmag": "j_mag",
    "Hmag": "h_mag",
    "Kmag": "k_mag",
    "distance": "separation",
    },
    "panstarrs_catalog_to_target_map": {
        "objID": "target_name",
        "raDeg": "ra_deg",
        "decDeg": "dec_deg",
        "epochMean": "epoch",
        "gMeanApMag": "g_mag",
        "rMeanApMag": "r_mag",
        "distance": "separation",
    },
    "sao2000_catalog_to_target_map": {
        "SaoNumber": "target_name",
        "RA": "ra",
        "Decl": "dec",
        "PMRA": "pm_ra",
        "PMDec": "pm_dec",
        "VMag": "v_mag",
        "distance": "separation",
    },
    "hip_catalog_to_target_map": {
        "HIP_ID": "target_name",
        "RA": "ra",
        "Decl": "dec",
        "pm_RA": "pm_ra",
        "pm_Dec": "pm_dec",
        "Vmag": "v_mag",
        // Tycho B_T rather than Johnson B - close enough to be useful to the
        // optical WFS, but not the same passband.
        "BT_Mag": "b_mag",
        "BV_Color": "b_m_v_mag",
        "distance": "separation",
    },
    "ucac4_catalog_to_target_map": {
        "UCAC_ID": "target_name",
        "RA": "ra",
        "Decl": "dec",
        "RA_deg": "ra_deg",
        "Decl_deg": "dec_deg",
        "PmRA": "pm_ra",
        "PmDec": "pm_dec",
        "2MASS_J": "j_mag",
        "2MASS_H": "h_mag",
        "2MASS_K": "k_mag",
        "APASS_B": "b_mag",
        "APASS_V": "v_mag",
        "APASS_g": "g_mag",
        "APASS_r": "r_mag",
        "distance": "separation",
    },
    "two_mass_catalog_to_target_map": {
        "2mass_ID": "target_name",
        "RA": "ra",
        "Decl": "dec",
        "JMag": "j_mag",
        "HMag": "h_mag",
        "KMag": "k_mag",
        "distance": "separation",
    },
    "gaia_catalog_to_target_map": {
        "ID": "target_name",
        "raDeg": "ra_deg",
        "decDeg": "dec_deg",
        "pmra": "pm_ra",
        "pmdec": "pm_dec",
        "g_mag": "g_mag",
        "b_mag": "b_mag",
        "r_mag": "r_mag",
        "distance": "separation",
    },
    // Fallback for any catalog that still returns the generic column names.
    "catalog_to_target_map": {
        "name": "target_name",
        "ra": "ra",
        "dec": "dec",
        "equinox": "equinox",
        "pm_ra": "pm_ra",
        "pm_dec": "pm_dec",
        "dra": "d_ra",
        "ddec": "d_dec",
        "jmag": "j_mag",
        "rmag": "r_mag",
        "vmag": "v_mag",
        "hmag": "h_mag",
        "kmag": "k_mag",
        "dist": "separation",
    },
    "table_column_width": 140,
    // A night's targets are shared across telescopes/programs; these are the hard caps.
    "full_night_target_limit": 378,
    "half_night_target_limit": 188,
    "duplicate_radec_tolerance_deg": 0.0001,
    "help_msg_filename": "helpMsg.md",
    "pi_logout_url": "https://www2.keck.hawaii.edu/inst/PILogin/homepage.php",
    "pi_portal_url": "https://www3.keck.hawaii.edu/observers/ObserverPortal/rel/index.html",
    "timezone": "Pacific/Honolulu",
    "time_format": "MM:DD HH:mm",
    "date_time_format": "YYYY/MM/DD HH:mm",
    "tel_lat_lng_el": {
        "Keck 1": {
            "lat": 19.8283,
            "lng": 204.5253,
            "el": 4.160
        },
        "Keck 2": {
            "lat": 19.8283,
            "lng": 204.5253,
            "el": 4.160
        }
    },
    "tel_geometry": {
        "Keck 1": {
            "r0": 0,
            "r1": 18,
            "r2": 0,
            "r3": 33.3,
            "t0": 0,
            "t1": 361,
            "t2": 5.3,
            "t3": 146.2,
            "left_north_wrap": 235,
            "right_south_wrap": 325,
            "trackLimit": 85
        },
        "Keck 2": {
            "r0": 0,
            "r1": 18,
            "r2": 0,
            "r3": 36.8,
            "t0": 0,
            "t1": 361,
            "t2": 185.3,
            "t3": 332.8,
            "left_north_wrap": 235,
            "right_south_wrap": 325,
            "trackLimit": 85
        }
    }
}